Update the generate script for libQt5Gui

diff --git a/generate b/generate
--- a/generate
+++ b/generate
@@ -36,6 +36,10 @@ rm -f libQt5Core/QtCore/mkspecs
 rm -rf libQt5Core/3rdparty
 rm -f libQt5Core/QtCore/testlib
 
+rm -rf libQt5Gui/QtGui/{*.h,Q*,*.orig}
+rm -f libQt5Gui/QtGui/mkspecs
+rm -rf libQt5Gui/3rdparty
+
 # Create output directories.
 #
 # 3rdparty/ has to be a sibling to QtCore/ because the QtCore source files use
@@ -50,6 +54,9 @@ mkdir Qt5Rcc/rcc/3rdparty
 mkdir -p libQt5Core/QtCore/private
 mkdir libQt5Core/3rdparty
 
+mkdir -p libQt5Gui/QtGui/private
+mkdir libQt5Gui/3rdparty
+
 # Directory for the MIME type database source XML file.
 #
 mkdir -p libQt5Core/QtCore/mimetypes/mime/packages
@@ -59,6 +66,7 @@ mkdir -p libQt5Core/QtCore/mimetypes/mime/packages
 ln -s ../../upstream/qtbase/mkspecs Qt5Moc/moc/
 ln -s ../../upstream/qtbase/mkspecs Qt5Rcc/rcc/
 ln -s ../../upstream/qtbase/mkspecs libQt5Core/QtCore/
+ln -s ../../upstream/qtbase/mkspecs libQt5Gui/QtGui/
 
 # Symlink the upstream third-party directories.
 #
@@ -68,6 +76,8 @@ ln -s ../../../upstream/qtbase/src/3rdparty/{freebsd,sha1} \
    Qt5Rcc/rcc/3rdparty/
 ln -s ../../upstream/qtbase/src/3rdparty/{easing,freebsd,forkfd,md4,md5,rfc6234,sha1,sha3,harfbuzz} \
    libQt5Core/3rdparty/
+ln -s ../../upstream/qtbase/src/3rdparty/icc \
+   libQt5Gui/3rdparty/
 
 # This is made necessary by the inclusion of
 # "../testlib/3rdparty/valgrind_p.h" by corelib/tools/qsimd.cpp. (That is,
@@ -195,11 +205,26 @@ for d in upstream/qtbase/src/corelib/*/; do
   symlink_module_subdir "libQt5Core" QtCore "$d"
 done
 
-# Symlink the upstream MIME type database source XML file.
+# Symlink the upstream QtGui sources into libQt5Gui/.
+#
+for d in upstream/qtbase/src/gui/*/; do
+  symlink_module_subdir "libQt5Gui" QtGui "$d"
+done
+
+# Symlink the upstream MIME type database source XML file into libQt5Core/.
 #
 ln -sf "../../../../../\
 upstream/qtbase/src/corelib/mimetypes/mime/packages/freedesktop.org.xml" \
 "libQt5Core/QtCore/mimetypes/mime/packages/"
+
+# Symlink upstream QtGui Qt resources and related files into libQt5Gui/.
+#
+ln -sf "../../../upstream/qtbase/src/gui/painting/qpdf.qrc" \
+       "libQt5Gui/QtGui/painting/"
+ln -sf "../../../upstream/qtbase/src/gui/painting/qpdfa_metadata.xml" \
+       "libQt5Gui/QtGui/painting/"
+ln -sf "../../../upstream/qtbase/src/gui/painting/webgradients.binaryjson" \
+       "libQt5Gui/QtGui/painting/"
 
 # Symlink all of the moc application's headers and source files into
 # Qt5Moc/moc/.
@@ -235,6 +260,11 @@ for f in upstream/qtbase/src/tools/rcc/*.{h,cpp}; do
   fi
 done
 
+# Extract the Qt version from upstream/qtbase/.qmake.conf.
+#
+qt_version="$(sed -nE 's%MODULE_VERSION = (.+)%\1%p' \
+                  upstream/qtbase/.qmake.conf)"
+
 # Copy headers generated by the upstream build into libQt5Core/QtCore/. (None
 # of these are required for the Qt5Moc build.)
 #
@@ -246,11 +276,6 @@ done
 # those headers that don't also exist in the upstream directory (in which case
 # they are not generated and will already have been symlinked above).
 #
-
-# Extract the Qt version from upstream/qtbase/.qmake.conf.
-#
-qt_version="$(sed -nE 's%MODULE_VERSION = (.+)%\1%p' \
-                  upstream/qtbase/.qmake.conf)"
 
 tmpdir="$(mktemp -d)"
 
@@ -273,3 +298,28 @@ for p in "$tmpdir/include/QtCore/"*; do
 done
 
 rm -r "$tmpdir"
+
+# Copy headers generated by the upstream build into libQt5Gui/QtGui/ (just
+# like we just did for QtCore).
+#
+tmpdir="$(mktemp -d)"
+
+if ! upstream/qtbase/bin/syncqt.pl \
+     -copy -module QtGui -version "$qt_version" \
+     -outdir "$tmpdir" upstream/qtbase \
+     > /dev/null; then
+  rm -r "$tmpdir"
+  error "syncqt.pl failed"
+fi
+
+# In addition to the generated public *.h and Q* headers as for QtCore, also
+# copy the generated QPA (Qt Platform Abstraction) headers.
+#
+for p in "$tmpdir/include/QtGui/"*; do
+  f="$(basename "$p")"
+  if [[ ("$f" == *.h && ! -e "libQt5Gui/QtGui/$f") || "$f" == Q* ]]; then
+    cp "$p" libQt5Gui/QtGui/
+  elif [[ "$f" == "$qt_version" ]]; then
+    cp -r "$p/QtGui/qpa/" libQt5Gui/QtGui/
+  fi
+done
