Update generate script for Qt5Plugins

diff --git a/generate b/generate
--- a/generate
+++ b/generate
@@ -6,7 +6,7 @@
 # Create the infrastructure required by our Qt packages:
 #
 # - Create a source layout more suitable to our purposes which is still
-#   compatible the Qt upstream (the way they include stuff, etc).
+#   compatible with the Qt upstream (the way they include stuff, etc).
 #
 
 owd="$(pwd)"
@@ -31,14 +31,21 @@ rm -rf Qt5Rcc/rcc/QtCore/
 rm -f Qt5Rcc/rcc/mkspecs
 rm -rf Qt5Rcc/rcc/3rdparty
 
-rm -rf libQt5Core/QtCore/{*.h,Q*,*.orig}
+rm -f libQt5Core/QtCore/{*.h,Q*,*.orig}
 rm -f libQt5Core/QtCore/mkspecs
 rm -rf libQt5Core/3rdparty
 rm -f libQt5Core/QtCore/testlib
 
-rm -rf libQt5Gui/QtGui/{*.h,Q*,*.orig}
+rm -f libQt5Gui/QtGui/{*.h,Q*,*.orig}
 rm -f libQt5Gui/QtGui/mkspecs
 rm -rf libQt5Gui/3rdparty
+
+rm -rf Qt5Plugins/plugins/{Qt*Support,QtPlatformHeaders}
+rm -f Qt5Plugins/plugins/mkspecs
+rm -f Qt5Plugins/plugins/platforms/xcb
+rm -f Qt5Plugins/plugins/platforms/platformsupport
+rm -f Qt5Plugins/plugins/platforminputcontexts/compose
+rm -f Qt5Plugins/plugins/imageformats/ico
 
 # Create output directories.
 #
@@ -67,6 +74,7 @@ ln -s ../../upstream/qtbase/mkspecs Qt5Moc/moc/
 ln -s ../../upstream/qtbase/mkspecs Qt5Rcc/rcc/
 ln -s ../../upstream/qtbase/mkspecs libQt5Core/QtCore/
 ln -s ../../upstream/qtbase/mkspecs libQt5Gui/QtGui/
+ln -s ../../upstream/qtbase/mkspecs Qt5Plugins/plugins/
 
 # Symlink the upstream third-party directories.
 #
@@ -211,6 +219,29 @@ for d in upstream/qtbase/src/gui/*/; do
   symlink_module_subdir "libQt5Gui" QtGui "$d"
 done
 
+# Symlink the upstream plugin sources into Qt5Plugins/plugins/.
+#
+# Note that we don't rearrange plugins' sources as we do those of "proper" Qt
+# modules such as QtCore and QtGui because it does not seem worth the trouble
+# for the following reasons: 1) The plugin directories have a different layout
+# in that there are source files in the plugin root (for example, in
+# upstream/qtbase/src/plugins/platforms/xcb/) which is where subdirectory
+# headers would be copied to, and 2) in some instances source files are more
+# than one directory level down from the root (for example, in
+# upstream/qtbase/src/plugins/platforms/xcb/gl_integrations/xcb_egl/). And 3)
+# the plugin libraries are loaded at runtime by one of the "proper" Qt modules
+# (for example, libQt5Gui loads libqxcb) and are thus not user-facing to the
+# same degree.
+#
+ln -s ../../../upstream/qtbase/src/platformsupport "Qt5Plugins/plugins/platforms/"
+
+for p in platforms/xcb \
+         platforminputcontexts/compose \
+         imageformats/ico; do
+  ln -s ../../../upstream/qtbase/src/plugins/"$p" \
+        "Qt5Plugins/plugins/$(dirname "$p")"
+done
+
 # Symlink the upstream MIME type database source XML file into libQt5Core/.
 #
 ln -sf "../../../../../\
@@ -265,31 +296,41 @@ done
 qt_version="$(sed -nE 's%MODULE_VERSION = (.+)%\1%p' \
                   upstream/qtbase/.qmake.conf)"
 
-# Copy headers generated by the upstream build into libQt5Core/QtCore/. (None
-# of these are required for the Qt5Moc build.)
+# Copy headers generated by the upstream build.
 #
 # The majority of the generated headers are camelcase versions of the public
-# headers (foobar.h -> QFooBar) but a few additional headers (public only) are
-# also generated.
+# headers (foobar.h -> QFooBar).
 #
 # Run the upstream syncqt.pl script to produce the include tree and copy only
 # those headers that don't also exist in the upstream directory (in which case
 # they are not generated and will already have been symlinked above).
 #
 
-tmpdir="$(mktemp -d)"
-
-if ! upstream/qtbase/bin/syncqt.pl \
-     -copy -module QtCore -version "$qt_version" \
-     -outdir "$tmpdir" upstream/qtbase \
-     > /dev/null; then
-  rm -r "$tmpdir"
-  error "syncqt.pl failed"
-fi
-
-# Copy those public *.h headers that have not already been symlinked and all
-# camelcase headers (of which all are generated and thus none symlinked).
+# Run the upstream syncqt.pl script to generate headers for the given Qt
+# module in a temporary directory.
 #
+# Return the path to the temporary directory.
+#
+function gen_hdrs () # <module-name>
+{
+  local mod="$1" # Module name.
+  local tmpdir="$(mktemp -d)"
+
+  if ! upstream/qtbase/bin/syncqt.pl               \
+       -copy -module "$mod" -version "$qt_version" \
+       -outdir "$tmpdir" upstream/qtbase           \
+       > /dev/null; then
+    rm -r "$tmpdir"
+    error "syncqt.pl failed"
+  fi
+
+  echo "$tmpdir"
+}
+
+# Copy headers generated for QtCore into libQt5Core/QtCore/.
+#
+tmpdir="$(gen_hdrs QtCore)"
+
 for p in "$tmpdir/include/QtCore/"*; do
   f="$(basename "$p")"
   if [[ ("$f" == *.h && ! -e "libQt5Core/QtCore/$f") || "$f" == Q* ]]; then
@@ -299,18 +340,13 @@ done
 
 rm -r "$tmpdir"
 
-# Copy headers generated by the upstream build into libQt5Gui/QtGui/ (just
-# like we just did for QtCore).
+# This (empty) header is generated by qmake in the upstream build.
 #
-tmpdir="$(mktemp -d)"
+touch libQt5Core/QtCore/QtCoreDepends
 
-if ! upstream/qtbase/bin/syncqt.pl \
-     -copy -module QtGui -version "$qt_version" \
-     -outdir "$tmpdir" upstream/qtbase \
-     > /dev/null; then
-  rm -r "$tmpdir"
-  error "syncqt.pl failed"
-fi
+# Copy headers generated for QtGui into libQt5Gui/QtGui/.
+#
+tmpdir="$(gen_hdrs QtGui)"
 
 # In addition to the generated public *.h and Q* headers as for QtCore, also
 # copy the generated QPA (Qt Platform Abstraction) headers.
@@ -322,4 +358,40 @@ for p in "$tmpdir/include/QtGui/"*; do
   elif [[ "$f" == "$qt_version" ]]; then
     cp -r "$p/QtGui/qpa/" libQt5Gui/QtGui/
   fi
+done
+
+rm -r "$tmpdir"
+
+# This header is generated by qmake in the upstream build.
+#
+echo "#include <QtCore/QtCore>" > libQt5Gui/QtGui/QtGuiDepends
+
+# Copy headers generated for the platform support modules (required by the
+# platform plugins) into Qt5Plugins/plugins/.
+#
+# Note: A few of these platform support modules are referenced from outside of
+# plugins/platforms/ so they have to reside at a higher level.
+#
+for mod in QtPlatformHeaders     \
+           QtServiceSupport      \
+           QtThemeSupport        \
+           QtFontDatabaseSupport \
+           QtXkbCommonSupport    \
+           QtEdidSupport; do
+  tmpdir="$(gen_hdrs "$mod")"
+
+  mkdir "Qt5Plugins/plugins/$mod/"
+  for p in "$tmpdir/include/$mod/"*; do
+    f="$(basename "$p")"
+    case "$f" in
+      *.h|Q*)        # Public header.
+        cp "$p" Qt5Plugins/plugins/"$mod"/
+        ;;
+      "$qt_version") # Private header directory.
+        cp -r "$p/$mod/private/" Qt5Plugins/plugins/"$mod"/
+        ;;
+    esac
+  done
+
+  rm -r "$tmpdir"
 done
