Update generate script

diff --git a/generate b/generate
--- a/generate
+++ b/generate
@@ -25,11 +25,13 @@ rm -f Qt5Moc/moc/*.{h,cpp,orig}
 rm -rf Qt5Moc/moc/QtCore/
 rm -f Qt5Moc/moc/mkspecs
 rm -rf Qt5Moc/moc/3rdparty
+rm -rf libQt5Core/QtCore/{*.h,Q*,*.orig}
+rm -f libQt5Core/QtCore/mkspecs
 
 # Create output directories.
 #
-mkdir Qt5Moc/moc/QtCore
-mkdir Qt5Moc/moc/QtCore/private
+mkdir -p Qt5Moc/moc/QtCore/private
+mkdir -p libQt5Core/QtCore/private
 
 # This directory has to be a sibling to QtCore/ because the QtCore source
 # files use include paths such as "../../3rdparty/freebsd/strtoll.c".
@@ -39,13 +41,14 @@ mkdir Qt5Moc/moc/3rdparty
 # Symlink the upstream platform-specific include directories.
 #
 ln -s ../../upstream/qtbase/mkspecs Qt5Moc/moc/
+ln -s ../../upstream/qtbase/mkspecs libQt5Core/QtCore/
 
 # Symlink the upstream third-party directories required to build moc.
 #
 ln -s ../../../upstream/qtbase/src/3rdparty/{freebsd,sha1} \
       Qt5Moc/moc/3rdparty/
 
-# Symlink all QtCore sources into Qt5Moc/moc/QtCore/.
+# Symlink all QtCore sources into <output-path-prefix>/QtCore/.
 #
 # Note that we have to rearrange the upstream sources because they cannot be
 # built the way they're laid out in upstream/qtbase/src/corelib/ (the upstream
@@ -68,32 +71,39 @@ ln -s ../../../upstream/qtbase/src/3rdparty/{freebsd,sha1} \
 #
 # create the following layout:
 #
-#   Qt5Moc
-#   └── moc
-#       └── QtCore
-#           ├── foo
-#           │   ├── foo.cpp
-#           │   ...
-#           ├── bar
-#           │   ├── bar.cpp
-#           │   ...
-#           ├── private
-#           │   ├── foo_p.h
-#           │   ├── bar_p.h
-#           │   ...
-#           ├── foo.h
-#           ├── bar.h
-#           ...
+#   <output-path-prefix>
+#    └── QtCore
+#        ├── foo
+#        │   ├── foo.cpp
+#        │   ...
+#        ├── bar
+#        │   ├── bar.cpp
+#        │   ...
+#        ├── private
+#        │   ├── foo_p.h
+#        │   ├── bar_p.h
+#        │   ...
+#        ├── foo.h
+#        ├── bar.h
+#        ...
 #
-for d in upstream/qtbase/src/corelib/*/; do
-  d="${d%/}" # Strip trailing /.
+function symlink_qtcore_subdir () # <output-path-prefix> <qtcore-dir>
+{
+  local opp="$1" # Output path prefix.
+  local d="$2"   # QtCore subdirectory from upstream.
 
-  sdd="Qt5Moc/moc/QtCore/$(basename $d)" # Source file destination directory.
-  mkdir "$sdd"
+  # Project directory path: the relative path to get to the project directory
+  # from the output path prefix (`opp`). For example, from Qt5Moc/moc/ it
+  # would be `../..`.
+  #
+  local pdp="$(sed -E 's%[^/]+%..%g' <<<"$opp")"
+  local sdd="$opp/QtCore/$(basename $d)" # Source file destination directory.
+  mkdir -p "$sdd"
 
   # All of the source files of interest are directly under one of
   # src/corelib/'s subdirectories (that is, nested no deeper).
   #
+  local f
   for f in "$d"/*; do
     f="${f#upstream/}" # Strip "upstream/" prefix.
 
@@ -103,20 +113,20 @@ for d in upstream/qtbase/src/corelib/*/; do
       # Private header.
       #
       *_p.h)
-        tpp="../../../.."
-        spp="Qt5Moc/moc/QtCore/private"
+        tpp="$pdp/../.."
+        spp="$opp/QtCore/private"
         ;;
       # Public header.
       #
       *.h)
-        tpp="../../.."
-        spp="Qt5Moc/moc/QtCore"
+        tpp="$pdp/.."
+        spp="$opp/QtCore"
         ;;
       # C++ source file.
       # Objective-C++ source file.
       #
       *.cpp | *.mm)
-        tpp="../../../.."
+        tpp="$pdp/../.."
         spp="$sdd"
         ;;
       # Not a source file.
@@ -128,12 +138,12 @@ for d in upstream/qtbase/src/corelib/*/; do
     # upstream filename while the upstream original's symlink gets the
     # upstream filename with a ".orig" extension.
     #
-    fn="$(basename "$f")" # File name.
+    local fn="$(basename "$f")" # File name.
     if [[ -f "downstream/$f" ]]; then
-      ln -s "$tpp/upstream/$f"   "$spp/$fn.orig"
-      ln -s "$tpp/downstream/$f" "$spp/$fn"
+      ln -sf "$tpp/upstream/$f"   "$spp/$fn.orig"
+      ln -sf "$tpp/downstream/$f" "$spp/$fn"
     else
-      ln -s "$tpp/upstream/$f"   "$spp/$fn"
+      ln -sf "$tpp/upstream/$f"   "$spp/$fn"
     fi
   done
 
@@ -143,6 +153,16 @@ for d in upstream/qtbase/src/corelib/*/; do
   if [[ -z "$(ls "$sdd")" ]]; then
     rmdir "$sdd"
   fi
+}
+
+# Symlink the upstream QtCore sources into Qt5Moc/ and libQt5Core/. Although
+# the Qt5Moc build includes only a subset of the QtCore sources we symlink all
+# of them for the sake of simplicity (its buildfile does not use wildcards).
+#
+for d in upstream/qtbase/src/corelib/*/; do
+  d="${d%/}" # Strip trailing /.
+  symlink_qtcore_subdir "Qt5Moc/moc" "$d"
+  symlink_qtcore_subdir "libQt5Core" "$d"
 done
 
 # Symlink all of the moc application's headers and source files into
@@ -161,3 +181,42 @@ for f in upstream/qtbase/src/tools/moc/*.{h,cpp}; do
     ln -s "../../upstream/$f"   "Qt5Moc/moc/$fn"
   fi
 done
+
+# Copy headers generated by the upstream build into libQt5Core/QtCore/. (None
+# of these are required for the Qt5Moc build.)
+#
+# The majority of the generated headers are camelcase versions of the public
+# headers (foobar.h -> QFooBar) but a few additional headers (public only) are
+# also generated.
+#
+# Run the upstream syncqt.pl script to produce the include tree and copy only
+# those headers that don't also exist in the upstream directory (in which case
+# they are not generated and will already have been symlinked above).
+#
+
+# Extract the Qt version from upstream/qtbase/.qmake.conf.
+#
+qt_version="$(sed -nE 's%MODULE_VERSION = (.+)%\1%p' \
+                  upstream/qtbase/.qmake.conf)"
+
+tmpdir="$(mktemp -d)"
+
+if ! upstream/qtbase/bin/syncqt.pl \
+     -copy -module QtCore -version "$qt_version" \
+     -outdir "$tmpdir" upstream/qtbase \
+     > /dev/null; then
+  rm -r "$tmpdir"
+  error "syncqt.pl failed"
+fi
+
+# Copy those public *.h headers that have not already been symlinked and all
+# camelcase headers (of which all are generated and thus none symlinked).
+#
+for p in "$tmpdir/include/QtCore/"*; do
+  f="$(basename "$p")"
+  if [[ ("$f" == *.h && ! -e "libQt5Core/QtCore/$f") || "$f" == Q* ]]; then
+    cp "$p" libQt5Core/QtCore/
+  fi
+done
+
+rm -r "$tmpdir"
