Update generate script

diff --git a/generate b/generate
--- a/generate
+++ b/generate
@@ -58,9 +58,7 @@ function rm_empty_dirs () # <dir>
   for sd in "$d"/*/; do
     # Remove subdirectory contents, then remove subdirectory itself if empty.
     #
-    if [[ -d "$sd" ]]; then
-      rm_empty_dirs "$sd"
-    fi
+    rm_empty_dirs "$sd"
 
     if [[ -z "$(ls "$sd")" ]]; then
       rmdir "$sd"
@@ -76,6 +74,9 @@ rm_empty_dirs Qt5Moc/moc/
 rm_symlinks Qt5Rcc/rcc/
 rm_empty_dirs Qt5Rcc/rcc/
 
+rm_symlinks Qt5Uic/uic/
+rm_empty_dirs Qt5Uic/uic/
+
 rm_symlinks libQt5Core/QtCore/
 rm_empty_dirs libQt5Core/QtCore/
 rm -f  libQt5Core/QtCore/Q*
@@ -85,39 +86,45 @@ rm_symlinks libQt5Gui/QtGui/
 rm_empty_dirs libQt5Gui/QtGui/
 rm -rf libQt5Gui/3rdparty
 rm -f  libQt5Gui/mkspecs
-# Remove copied headers (generated by syncqt.pl).
-#
 rm -rf libQt5Gui/QtGui/qpa/
 rm -rf libQt5Gui/QtGui/private/QtGui/qpa/
-rm -f   libQt5Gui/QtGui/Q*
+rm -f  libQt5Gui/QtGui/Q*
 
 rm_symlinks libQt5Gui/QtGuiPlugins/
 rm_empty_dirs libQt5Gui/QtGuiPlugins/
 rm -rf libQt5Gui/QtGuiPlugins/{Qt*Support,QtPlatformHeaders}
+
+rm -f libQt5GuiTests/mkspecs
+
+rm -f libQt5Widgets/mkspecs
+rm -rf libQt5Widgets/QtWidgets/QtPlatformHeaders
+rm_symlinks libQt5Widgets/QtWidgets/
+rm_empty_dirs libQt5Widgets/QtWidgets/
+rm -f  libQt5Widgets/QtWidgets/Q*
+
+rm_symlinks libQt5Widgets/QtWidgetsPlugins/
+rm_empty_dirs libQt5Widgets/QtWidgetsPlugins/
+
+rm_symlinks libQt5WidgetsTests/gui-app
+rm -f libQt5WidgetsTests/mkspecs
 
 # Create output directories.
 #
 # 3rdparty/ has to be a sibling to QtCore/ because the QtCore source files use
 # include paths such as "../../3rdparty/freebsd/strtoll.c".
 #
-mkdir Qt5Moc/moc/3rdparty
-mkdir Qt5Moc/moc/QtCore
-mkdir Qt5Moc/moc/QtCore/private
-mkdir Qt5Moc/moc/QtCore/private/QtCore
-mkdir Qt5Moc/moc/QtCore/private/QtCore/private
+mkdir    Qt5Moc/moc/3rdparty
+mkdir    Qt5Moc/moc/QtCore
+mkdir -p Qt5Moc/moc/QtCore/private/QtCore/private
 
-mkdir Qt5Rcc/rcc/3rdparty
-mkdir Qt5Rcc/rcc/QtCore
-mkdir Qt5Rcc/rcc/QtCore/private
-mkdir Qt5Rcc/rcc/QtCore/private/QtCore
-mkdir Qt5Rcc/rcc/QtCore/private/QtCore/private
+mkdir    Qt5Rcc/rcc/3rdparty
+mkdir    Qt5Rcc/rcc/QtCore
+mkdir -p Qt5Rcc/rcc/QtCore/private/QtCore/private
 
 mkdir libQt5Core/3rdparty
 # Directory for the MIME type database source XML file.
 #
-mkdir libQt5Core/QtCore/mimetypes
-mkdir libQt5Core/QtCore/mimetypes/mime
-mkdir libQt5Core/QtCore/mimetypes/mime/packages
+mkdir -p libQt5Core/QtCore/mimetypes/mime/packages
 
 mkdir libQt5Gui/3rdparty
 mkdir libQt5Gui/QtGui/qpa
@@ -127,8 +134,12 @@ mkdir libQt5Gui/QtGui/private/QtGui/qpa
 #
 ln -s ../../upstream/qtbase/mkspecs Qt5Moc/moc/
 ln -s ../../upstream/qtbase/mkspecs Qt5Rcc/rcc/
+ln -s ../../upstream/qtbase/mkspecs Qt5Uic/uic/
 ln -s ../../upstream/qtbase/mkspecs libQt5Core/QtCore/
-ln -s ../upstream/qtbase/mkspecs libQt5Gui/
+ln -s    ../upstream/qtbase/mkspecs libQt5Gui/
+ln -s    ../upstream/qtbase/mkspecs libQt5GuiTests/
+ln -s    ../upstream/qtbase/mkspecs libQt5Widgets/
+ln -s    ../upstream/qtbase/mkspecs libQt5WidgetsTests/
 
 # Symlink the upstream third-party directories.
 #
@@ -138,15 +149,8 @@ ln -s ../../../upstream/qtbase/src/3rdparty/{freebsd,sha1} \
    Qt5Rcc/rcc/3rdparty/
 ln -s ../../upstream/qtbase/src/3rdparty/{easing,freebsd,forkfd,md4,md5,rfc6234,sha1,sha3,harfbuzz} \
    libQt5Core/3rdparty/
-ln -s ../../upstream/qtbase/src/3rdparty/icc \
+ln -s ../../upstream/qtbase/src/3rdparty/{icc,wintab} \
    libQt5Gui/3rdparty/
-
-# This is made necessary by the inclusion of
-# "../testlib/3rdparty/valgrind_p.h" by corelib/tools/qsimd.cpp. (That is,
-# QtCore includes a private header from QTestLib, an entirely different
-# library...)
-#
-ln -sf ../../upstream/qtbase/src/testlib libQt5Core/QtCore/
 
 # Symlink an upstream source file into our project directory structure.
 #
@@ -188,26 +192,64 @@ function symlink_source_file () # <symlink-target-path> <destination-dir-path>
   fi
 }
 
-# Symlink the moc and rcc applications' headers and source files into
-# Qt5Moc/moc/ and Qt5Rcc/rcc/. Unlike Qt modules such as QtCore and QtGui (see
-# below), these tools' source files and headers are all in the same directory.
+# Symlink the sources of an upstream non-module.
 #
-for f in upstream/qtbase/src/tools/moc/*.{h,cpp}; do
-  symlink_source_file "../../$f" Qt5Moc/moc/
-done
+# Non-modules include tools, plugins, and internal modules such as those in
+# upstream/qtbase/src/platformsupport/.
+#
+# Note that we don't rearrange non-modules' sources as we do those of "proper"
+# Qt modules such as QtCore and QtGui because it does not seem worth the
+# trouble for the following reasons: 1) These subprojects have a different
+# layout in that there are source files in the root directory (for example, in
+# upstream/qtbase/src/plugins/platforms/xcb/) which is where subdirectory
+# headers would be copied to, and 2) in some instances source files are more
+# than one directory level down from the root (for example, in
+# upstream/qtbase/src/plugins/platforms/xcb/gl_integrations/xcb_egl/). And 3)
+# tools are not libraries while the plugin libraries are loaded at runtime by
+# one of the "proper" Qt modules (for example, libQt5Gui loads libqxcb) and
+# are thus not user-facing to the same degree.
+#
+function symlink_non_module () # <source-directory> <destination-directory>
+{
+  local s="${1%/}"                  # Source directory.
+  local d="${2%/}/$(basename "$s")" # Destination directory.
 
-for f in upstream/qtbase/src/tools/rcc/*.{h,cpp}; do
-  symlink_source_file "../../$f" Qt5Rcc/rcc/
-done
+  # Prefix to make target path relative to the destination directory (one
+  # `../` for each directory component in the destination path).
+  #
+  local tp="$(sed -Ee 's%[^/]+%..%g' <<<"$d")" # Target prefix.
 
-# Symlink all of a Qt module's sources into
-# <output-path-prefix>/<module-name>/.
+  local t # Target file.
+  for t in "$s"/*; do
+    case "$t" in
+      *.h|*.cpp|*.mm|*.json)
+        symlink_source_file "$tp/$t" "$d"
+        ;;
+      *)
+        if [[ -d "$t" ]]; then
+          local sp="$d/$(basename "$t")" # Directory symlink path.
+          mkdir -p "$sp"
+          symlink_non_module "$t" "$d"
+          # Remove the directory if it's empty (contained no interesting
+          # files).
+          #
+          if [[ -z "$(ls "$sp")" ]]; then
+            rmdir "$sp"
+          fi
+        fi
+    esac
+  done
+}
+
+# Symlink all of the sources in a Qt module subdirectory into
+# <output-path-prefix>/<module-name>/<subdir>.
 #
 # Note that we have to rearrange the upstream sources because they cannot be
 # built the way they're laid out in upstream/qtbase/src/<module> (the upstream
 # build also rearranges them).
 #
-# From the upstream directory layout:
+# From the upstream directory layout (after the repeated application of this
+# function to all of a module's subdirectories):
 #
 #   upstream/qtbase/src/modulename
 #   ├── foo
@@ -298,6 +340,16 @@ function symlink_module_subdir ()
   fi
 }
 
+# Symlink the moc, rcc, and uic applications' headers and source files into
+# Qt5Moc/moc/, Qt5Rcc/rcc/, and Qt5Uic/uic/.
+#
+symlink_non_module upstream/qtbase/src/tools/moc \
+                   Qt5Moc/
+symlink_non_module upstream/qtbase/src/tools/rcc \
+                   Qt5Rcc/
+symlink_non_module upstream/qtbase/src/tools/uic \
+                   Qt5Uic/
+
 # Symlink the upstream QtCore sources into Qt5Moc/, Qt5Rcc/, and
 # libQt5Core/. Although the Qt5Moc and Qt5Rcc builds include only a subset of
 # the QtCore sources we symlink all of them for the sake of simplicity (their
@@ -315,6 +367,11 @@ ln -s ../../../../../\
 upstream/qtbase/src/corelib/mimetypes/mime/packages/freedesktop.org.xml \
       libQt5Core/QtCore/mimetypes/mime/packages/
 
+# This is made necessary by the inclusion of
+# "../testlib/3rdparty/valgrind_p.h" by corelib/tools/qsimd.cpp.
+#
+ln -sf ../../upstream/qtbase/src/testlib libQt5Core/QtCore/
+
 # Symlink the upstream QtGui sources into libQt5Gui/.
 #
 for d in upstream/qtbase/src/gui/*/; do
@@ -330,7 +387,8 @@ rm libQt5Gui/QtGui/private/QtGui/private/qplatform*_p.h
 mv libQt5Gui/QtGui/kernel/qguiapplication.cpp \
    libQt5Gui/QtGui/kernel/qguiapplication-install.cpp
 
-# Symlink upstream Qt resources and related files into libQt5Gui/.
+# Symlink upstream Qt resource collection files and their associated resources
+# into libQt5Gui/.
 #
 ln -s ../../../upstream/qtbase/src/gui/painting/qpdf.qrc \
       libQt5Gui/QtGui/painting/
@@ -339,57 +397,42 @@ ln -s ../../../upstream/qtbase/src/gui/painting/qpdfa_metadata.xml \
 ln -s ../../../upstream/qtbase/src/gui/painting/webgradients.binaryjson \
       libQt5Gui/QtGui/painting/
 
-# Symlink upstream plugin sources.
+symlink_non_module upstream/qtbase/src/platformsupport \
+                   libQt5Gui/QtGuiPlugins/platforms/
+
+symlink_non_module upstream/qtbase/src/plugins/platforms/xcb/ \
+                   libQt5Gui/QtGuiPlugins/platforms/
+
+symlink_non_module upstream/qtbase/src/plugins/platforms/cocoa/ \
+                   libQt5Gui/QtGuiPlugins/platforms/
+
+symlink_non_module upstream/qtbase/src/plugins/platforms/windows/ \
+                   libQt5Gui/QtGuiPlugins/platforms/
+
+# Symlink the Cocoa plugin's resource collection file and its associated
+# resources.
 #
-# Note that we don't rearrange plugins' sources as we do those of "proper" Qt
-# modules such as QtCore and QtGui because it does not seem worth the trouble
-# for the following reasons: 1) The plugin directories have a different layout
-# in that there are source files in the plugin root (for example, in
-# upstream/qtbase/src/plugins/platforms/xcb/) which is where subdirectory
-# headers would be copied to, and 2) in some instances source files are more
-# than one directory level down from the root (for example, in
-# upstream/qtbase/src/plugins/platforms/xcb/gl_integrations/xcb_egl/). And 3)
-# the plugin libraries are loaded at runtime by one of the "proper" Qt modules
-# (for example, libQt5Gui loads libqxcb) and are thus not user-facing to the
-# same degree.
+ln -s ../../../../upstream/qtbase/src/plugins/platforms/cocoa/qcocoaresources.qrc \
+      libQt5Gui/QtGuiPlugins/platforms/cocoa/
+ln -s ../../../../upstream/qtbase/src/plugins/platforms/cocoa/images/ \
+      libQt5Gui/QtGuiPlugins/platforms/cocoa/
+
+# Symlink the Windows plugin's resource collection files and their associated
+# resources.
 #
-function symlink_plugin_files ()
-{
-  local s="${1%/}"                  # Source directory.
-  local d="${2%/}/$(basename "$s")" # Destination directory.
+ln -s ../../../../upstream/qtbase/src/plugins/platforms/windows/cursors.qrc \
+      libQt5Gui/QtGuiPlugins/platforms/windows/
+ln -s ../../../../upstream/qtbase/src/plugins/platforms/windows/images/ \
+      libQt5Gui/QtGuiPlugins/platforms/windows/
+ln -s ../../../../upstream/qtbase/src/plugins/platforms/windows/openglblacklists.qrc \
+      libQt5Gui/QtGuiPlugins/platforms/windows/
 
-  # Prefix to make target path relative to the destination directory (one
-  # `../` for each directory component in the destination path).
-  #
-  local tp="$(sed -Ee 's%[^/]+%..%g' <<<"$d")" # Target prefix.
-
-  local t # Target file.
-  for t in "$s"/*; do
-    case "$t" in
-      *.h|*.cpp|*.json)
-        symlink_source_file "$tp/$t" "$d"
-        ;;
-      *)
-        if [[ -d "$t" ]]; then
-          mkdir -p "$d/$(basename "$t")"
-          symlink_plugin_files "$t" "$d"
-        fi
-    esac
-  done
-}
-
-symlink_plugin_files upstream/qtbase/src/platformsupport \
-                     libQt5Gui/QtGuiPlugins/platforms/
-
-symlink_plugin_files upstream/qtbase/src/plugins/platforms/xcb/ \
-                     libQt5Gui/QtGuiPlugins/platforms/
-
-symlink_plugin_files \
+symlink_non_module \
   upstream/qtbase/src/plugins/platforminputcontexts/compose/ \
   libQt5Gui/QtGuiPlugins/platforminputcontexts/
 
-# For the imageformats plugins we symlink the source directories, not their
-# contents.
+# Symlink directly to the imageformats plugins' directories (not their
+# contents).
 #
 ln -s ../../../upstream/qtbase/src/plugins/imageformats/gif \
       libQt5Gui/QtGuiPlugins/imageformats/
@@ -397,6 +440,39 @@ ln -s ../../../upstream/qtbase/src/plugins/imageformats/ico \
       libQt5Gui/QtGuiPlugins/imageformats/
 ln -s ../../../upstream/qtbase/src/plugins/imageformats/jpeg \
       libQt5Gui/QtGuiPlugins/imageformats/
+
+# Symlink the upstream QtWidgets sources into libQt5Widgets/.
+#
+for d in upstream/qtbase/src/widgets/*/; do
+  symlink_module_subdir libQt5Widgets QtWidgets "$d"
+done
+
+mv libQt5Widgets/QtWidgets/kernel/qapplication.cpp \
+   libQt5Widgets/QtWidgets/kernel/qapplication-install.cpp
+
+# Symlink upstream Qt resources collection files and their associated
+# resources into libQt5Widgets/.
+#
+ln -s ../../../upstream/qtbase/src/widgets/dialogs/qmessagebox.qrc \
+      libQt5Widgets/QtWidgets/dialogs/
+ln -s ../../../upstream/qtbase/src/widgets/styles/qstyle.qrc \
+      libQt5Widgets/QtWidgets/styles/
+ln -s ../../../upstream/qtbase/src/widgets/styles/images \
+      libQt5Widgets/QtWidgets/styles/
+ln -s ../../../upstream/qtbase/src/widgets/dialogs/qfiledialog.ui \
+      libQt5Widgets/QtWidgets/dialogs/
+ln -s ../../../upstream/qtbase/src/widgets/dialogs/images \
+      libQt5Widgets/QtWidgets/dialogs/
+
+ln -s ../../upstream/qtbase/examples/widgets/widgets/spinboxes/window.h \
+      libQt5WidgetsTests/gui-app/
+ln -s ../../upstream/qtbase/examples/widgets/widgets/spinboxes/window.cpp \
+      libQt5WidgetsTests/gui-app/
+
+symlink_non_module upstream/qtbase/src/plugins/styles/mac/ \
+                   libQt5Widgets/QtWidgetsPlugins/styles/
+symlink_non_module upstream/qtbase/src/plugins/styles/windowsvista/ \
+                   libQt5Widgets/QtWidgetsPlugins/styles/
 
 # Extract the Qt version from upstream/qtbase/.qmake.conf.
 #
@@ -407,7 +483,7 @@ qt_version="$(sed -nE 's%MODULE_VERSION = (.+)%\1%p' \
 #
 # The majority of the generated headers are camelcase versions of the public
 # headers (foobar.h -> QFooBar) but in some cases headers from different
-# subdirectories are placed in the same directory to allow their inclusion
+# subdirectories are copied to a single directory to allow their inclusion
 # using a common path prefix.
 #
 # Run the upstream syncqt.pl script to produce the include tree and copy only
@@ -423,7 +499,10 @@ qt_version="$(sed -nE 's%MODULE_VERSION = (.+)%\1%p' \
 function gen_hdrs () # <module-name>
 {
   local mod="$1" # Module name.
-  local tmpdir="$(mktemp -d)"
+  local tmpdir
+  if ! tmpdir="$(mktemp -d)"; then
+    error "mktemp failed"
+  fi
 
   if ! upstream/qtbase/bin/syncqt.pl               \
        -copy -module "$mod" -version "$qt_version" \
@@ -487,7 +566,11 @@ rm -r "$tmpdir"
 
 # This header is generated by qmake in the upstream build.
 #
-echo "#include <QtCore/QtCore>" > libQt5Gui/QtGui/QtGuiDepends
+cat > libQt5Gui/QtGui/QtGuiDepends << EOF
+#ifdef __cplusplus /* create empty PCH in C mode */
+#include <QtCore/QtCore>
+#endif
+EOF
 
 # Copy headers generated for the platform support modules (required by the
 # code in platformsupport/ and the platform plugins via includes such as
@@ -499,12 +582,18 @@ echo "#include <QtCore/QtCore>" > libQt5Gui/QtGui/QtGuiDepends
 #       Currently only one out of many camelcase platform support headers
 #       (QPlatformHeaderHelper) is actually referenced by the code.
 #
-for mod in QtPlatformHeaders     \
-           QtServiceSupport      \
-           QtThemeSupport        \
-           QtFontDatabaseSupport \
-           QtXkbCommonSupport    \
-           QtEdidSupport; do
+for mod in QtAccessibilitySupport       \
+           QtClipboardSupport           \
+           QtEdidSupport                \
+           QtEventDispatcherSupport     \
+           QtFontDatabaseSupport        \
+           QtGraphicsSupport            \
+           QtPlatformHeaders            \
+           QtPrintSupport               \
+           QtServiceSupport             \
+           QtThemeSupport               \
+           QtWindowsUIAutomationSupport \
+           QtXkbCommonSupport; do
   tmpdir="$(gen_hdrs "$mod")"
 
   mkdir "libQt5Gui/QtGuiPlugins/$mod/"
@@ -518,6 +607,52 @@ for mod in QtPlatformHeaders     \
         ;;
       "$qt_version") # Private header directory.
         cp -r "$p/$mod/private/" "libQt5Gui/QtGuiPlugins/$mod/"
+        ;;
+    esac
+  done
+
+  rm -r "$tmpdir"
+done
+
+# Copy headers generated for QtWidgets into libQt5Widgets/QtWidgets/.
+#
+tmpdir="$(gen_hdrs QtWidgets)"
+
+for p in "$tmpdir/include/QtWidgets/"*; do
+  f="$(basename "$p")"
+
+  if [[ ("$f" == *.h && ! -e "libQt5Widgets/QtWidgets/$f") || "$f" == Q* ]]; then
+    cp "$p" libQt5Widgets/QtWidgets/
+  fi
+done
+
+rm -r "$tmpdir"
+
+# This header is generated by qmake in the upstream build.
+#
+cat > libQt5Widgets/QtWidgets/QtWidgetsDepends << EOF
+#ifdef __cplusplus /* create empty PCH in C mode */
+#include <QtCore/QtCore>
+#include <QtGui/QtGui>
+#endif
+EOF
+
+# Copy generated platform headers to libQt5Widgets/QtWidgets.
+#
+for mod in QtPlatformHeaders; do
+  tmpdir="$(gen_hdrs "$mod")"
+
+  mkdir "libQt5Widgets/QtWidgets/$mod/"
+
+  for p in "$tmpdir/include/$mod/"*; do
+    f="$(basename "$p")"
+
+    case "$f" in
+      *.h|QPlatformHeaderHelper) # Public header.
+        cp "$p" "libQt5Widgets/QtWidgets/$mod/"
+        ;;
+      "$qt_version") # Private header directory.
+        cp -r "$p/$mod/private/" "libQt5Widgets/QtWidgets/$mod/"
         ;;
     esac
   done
